### ISSUE TITLE
Missing dad

### ISSUE THREAD

**Issue by zenflow** [zenflow/sweetalert2-react#2]
HI @alex-shamshurin! This is your baby right? You integrated [sweetalert2](https://github.com/sweetalert2/sweetalert2) into [chentsulin/sweetalert-react](https://github.com/chentsulin/sweetalert-react).

But you have turned off issues for your repo 😢 

Any interest in any level of helping to continue to maintain?

We *may* want to at some point move this under the [sweetalert2 org](https://github.com/sweetalert2). If so we would likely welcome you as a member :) We have a cool little team there.

Cheers!

**Comment by alex-shamshurin** [comment]
I turned issues on, sorry for that. Of course, I can join

**Comment by zenflow** [comment]
Great to hear! First we need to evaluate this package as a team. I haven't tried it out yet, but on the surface it looks great! (Besides missing tests).

I will call out to the rest of the team to check out your project 👍
